// Particle System plug-in for WADE (version 1.0.1) - Copyright Clockwork Chilli ltd 2012-2014 - all rights reserved. You must obtain a valid license at www.clockworkchilli.com to redistribute this file 
Wade_particles=function(){var n=this,h={},f=[],j=[],d=-1!=navigator.userAgent.indexOf("Firefox");this.splitImageChannels=function(a,p){var k="__wade_particles_"+a+"_r",d="__wade_particles_"+a+"_g",b="__wade_particles_"+a+"_b";if(p||"ok"!=wade.getLoadingStatus(k)||"ok"!=wade.getLoadingStatus(d)||"ok"!=wade.getLoadingStatus(b)){for(var g=wade.getImageData(a),h=g.width,e=g.height,g=g.data,f=[{name:k},{name:d},{name:b}],c=0;3>c;c++){var i=document.createElement("canvas");i.width=h;i.height=e;var j=i.getContext("2d"),
q=j.getImageData(0,0,h,e),l=q.data;f[c].canvas=i;f[c].context=j;f[c].imageData=q;f[c].data=l}h=4*h*e;for(c=0;c<h;c+=4)for(e=0;3>e;e++)f[e].data[c+e]=g[c+e],f[e].data[c+3]=g[c+3];for(c=0;3>c;c++)f[c].context.putImageData(f[c].imageData,0,0),wade.setImage(f[c].name,f[c].canvas)}return{r:k,g:d,b:b}};var g={x:0,y:0};this.forces={attractQuadratic_:function(a,p){return function(k,d){g.x=k;g.y=d;var b=wade.vec2.sub(a,g);return wade.vec2.scale(b,p*wade.vec2.length(b))}},attractLinear_:function(a,p){return function(k,
d){g.x=k;g.y=d;var b=wade.vec2.sub(a,g);return wade.vec2.scale(b,p)}},attractConstant_:function(a,p){return function(d,b){g.x=d;g.y=b;var f=wade.vec2.sub(a,g);return wade.vec2.scale(wade.vec2.normalizeIfPossible(f),p)}},repelQuadratic_:function(a,p){return function(d,b){g.x=d;g.y=b;var f=wade.vec2.sub(a,g);return wade.vec2.scale(f,-p*wade.vec2.length(f))}},repelLinear_:function(a,p){return function(d,b){g.x=d;g.y=b;var f=wade.vec2.sub(a,g);return wade.vec2.scale(f,-p)}},repelConstant_:function(a,
p){return function(d,b){g.x=d;g.y=b;var f=wade.vec2.sub(a,g);return wade.vec2.scale(wade.vec2.normalizeIfPossible(f),-p)}},tangent_:function(a,d){return function(b,f){g.x=b;g.y=f;var h=wade.vec2.sub(a,g);return wade.vec2.scale({x:h.y,y:-h.x},d)}}};this.addParticle=function(a){a=a||{};a={colorR:a.colorR||[],colorG:a.colorG||[],colorB:a.colorB||[],colorA:a.colorA||[{time:0,value:1}],sizeX:a.sizeX||[{time:0,value:16}],sizeY:a.sizeY||[{time:0,value:16}],drag:a.drag||[{time:0,value:0}],velocityX:a.velocityX||
0,velocityY:a.velocityY||0,angularVelocity:a.angularVelocity||0,rotation:a.rotation||0,positionX:a.positionX||0,positionY:a.positionY||0,maxLifetime:a.lifetime||1,image:a.image,forces:a.forces||[],layer:a.layer||1,additive:"undefined"!=typeof a.additive?!!a.additive:!0,lifetime:0};if(a.colorR.length&&a.colorG.length&&a.colorB.length){var d=wade.particles.splitImageChannels(a.image);if(1==a.colorR.length&&1==a.colorG.length&&1==a.colorB.length&&(1!=a.colorR[0].value||1!=a.colorG[0].value||1!=a.colorB[0].value)){var k=
new Sprite(d.r,a.layer);k.setDrawFunction(wade.drawFunctions.alpha_(a.colorR[0].value,k.draw));var g=new Sprite(d.g,a.layer);g.setDrawFunction(wade.drawFunctions.alpha_(a.colorG[0].value,k.draw));d=new Sprite(d.b,a.layer);d.setDrawFunction(wade.drawFunctions.alpha_(a.colorB[0].value,k.draw));k.cache();a.image=k.getImageName();g.drawToImage(a.image,!1);d.drawToImage(a.image,!1)}else a.images=d}a.red=a.colorR.length?a.colorR[0].value:1;a.green=a.colorG.length?a.colorG[0].value:1;a.blue=a.colorB.length?
a.colorB[0].value:1;a.alpha=a.colorA.length?a.colorA[0].value:1;a.actualSizeX=a.sizeX[0].value;a.actualSizeY=a.sizeY[0].value;a.image=wade.getImage(a.image);a.images&&(a.images.r=wade.getImage(a.images.r),a.images.g=wade.getImage(a.images.g),a.images.b=wade.getImage(a.images.b));!h[a.layer]||!j[a.layer].getSceneObject()||!j[a.layer].getSceneObject().isInScene()?(h[a.layer]=[a],-1==f.indexOf(a.layer)&&f.push(a.layer),k=new Sprite(null,a.layer),k.setDrawFunction(b(a.layer)),j[a.layer]=k,wade.addSceneObject(new SceneObject(k))):
h[a.layer].push(a);return a};this.removeParticle=function(a){wade.removeObjectFromArray(a,h[a.layer])};this.removeAllParticles=function(){for(var a=0;a<f.length;a++)h[f[a]].length=0};this.step=function(a){for(var d=0;d<f.length;d++){for(var b=h[f[d]],g=99999999,v=99999999,s=99999999,r=99999999,e=0,w=b.length-1;0<=w;w--){var c=b[w];c.lifetime+=a;if(c.lifetime>=c.maxLifetime)this.removeParticle(c),g=Math.min(g,c.positionX-c.actualSizeX/2),s=Math.min(s,c.positionY-c.actualSizeY/2),v=Math.max(v,c.positionX+
c.actualSizeX/2),r=Math.max(r,c.positionY+c.actualSizeY/2),e++;else{var i=c.lifetime/c.maxLifetime;c.positionX+=a*c.velocityX;c.positionY+=a*c.velocityY;c.rotation+=a*c.angularVelocity;for(var m=0,q=0,l=0,t=0;t<c.forces.length;t++)var n="function"==typeof c.forces[t]?c.forces[t](c.positionX,c.positionY):c.forces[t],m=m+(n.x||0),q=q+(n.y||0),l=l+(n.angle||0);t=u(c.drag,i);m-=t*c.velocityX;q-=t*c.velocityY;l-=t*c.angularVelocity;c.velocityX+=m*a;c.velocityY+=q*a;c.angularVelocity+=l*a;c.images&&(c.red=
u(c.colorR,i),c.green=u(c.colorG,i),c.blue=u(c.colorB,i));c.alpha=u(c.colorA,i);c.actualSizeX=u(c.sizeX,i);c.actualSizeY=u(c.sizeY,i);g=Math.min(g,c.positionX-c.actualSizeX/2);s=Math.min(s,c.positionY-c.actualSizeY/2);v=Math.max(v,c.positionX+c.actualSizeX/2);r=Math.max(r,c.positionY+c.actualSizeY/2)}}if(b.length||e)b=j[f[d]],b.setPosition((g+v)/2,(s+r)/2),b.setSize(v-g,r-s),b.setDirtyArea()}};var b=function(a){return function(b){for(var f=b.globalAlpha,g=b.globalCompositeOperation,j=g,s=h[a],r=0;r<
s.length;r++){var e=s[r];b.globalAlpha=e.alpha;e.rotation&&(b.save(),b.translate(e.positionX,e.positionY),b.rotate(e.rotation),b.translate(-e.positionX,-e.positionY));if(e.images){var n=e.positionX-e.actualSizeX/2,c=e.positionY-e.actualSizeY/2,i=e.actualSizeX,m=e.actualSizeY;if(e.additive)wade.numDrawCalls+=3,!d&&"lighter"!=j&&(b.globalCompositeOperation=j="lighter"),b.globalAlpha=e.red*e.alpha,b.drawImage(e.images.r,n,c,i,m),b.globalAlpha=e.green*e.alpha,b.drawImage(e.images.g,n,c,i,m),b.globalAlpha=
e.blue*e.alpha,b.drawImage(e.images.b,n,c,i,m);else{wade.numDrawCalls+=4;var q=document.createElement("canvas"),l=q.getContext("2d");q.width=i;q.height=m;l.globalAlpha=e.red;l.drawImage(e.images.r,0,0,i,m);!d&&(l.globalCompositeOperation="lighter");l.globalAlpha=e.green;l.drawImage(e.images.g,0,0,i,m);l.globalAlpha=e.blue;l.drawImage(e.images.b,0,0,i,m);"source-over"!=j&&(b.globalCompositeOperation=j="source-over");b.globalAlpha=e.alpha;b.drawImage(q,n,c,i,m)}}else wade.numDrawCalls++,b.globalAlpha=
e.alpha,b.drawImage(e.image,e.positionX-e.actualSizeX/2,e.positionY-e.actualSizeY/2,e.actualSizeX,e.actualSizeY);this._rotation&&b.restore()}b.globalAlpha=f;b.globalCompositeOperation=g}},u=function(a,b){for(var d=1;d<a.length;d++)if(b>=a[d-1].time&&b<=a[d].time){var f=(b-a[d-1].time)/(a[d].time-a[d-1].time);return a[d-1].value*(1-f)+a[d].value*f}return b>=a[a.length-1].time?a[a.length-1].value:a[0].value};this.init=function(){wade.requireVersion("1.3.3","alert","The Particle Plug-in requires version 1.3.3 of WADE (or newer).\nPlease upgrade at www.clockworkchilli.com");
d&&wade.log("Additive blending for particles may look wrong in this browser, due to the lack of hardware-acceleratetion support");wade.setMainLoopCallback(function(){n.step(wade.c_timeStep)},"__wade_particles")};this.forceCompositeOperations=function(a){"undefined"==typeof a&&(a=!0);d=-1!=navigator.userAgent.indexOf("Firefox")&&!a}};wade.particles=new Wade_particles;
Emitter=function(){var n=0;this.name="Emitter";this.particleImage="procedural_fadingCircle";this.emissionRate={min:3,max:3};this.particleLifetime={min:10,max:10};this.particleVelocity={min:{x:0,y:0},max:{x:0,y:0}};this.particleSpin={min:0,max:0};this.particleDrag=[{time:0,min:0,max:0}];this.particleSize=[{time:0,min:{x:32,y:32},max:{x:32,y:32}}];this.particleColor=[{time:0,min:{r:1,g:1,b:1,a:1},max:{r:1,g:1,b:1,a:1}}];this.area={minX:0,minY:0,maxX:0,maxY:0};this.initialRotation={min:0,max:0};this.additive=
this.inheritEmitterMotion=!0;this.layer=1;this.forces=[];this.emitOnce=this.emitterLifetime=0;this.onAddToScene=function(f){if(f&&f.emitter)for(var h in this)this.hasOwnProperty(h)&&(this[h]=f.emitter[h]||this[h]);this.emitOnce&&(this.emit(this.emitOnce),wade.removeSceneObject(this.owner))};this.emit=function(f){var j,d,g=this.owner.getPosition();for(j=0;j<f;j++){var b={};if(this.particleColor&&this.particleColor.length&&(1<this.particleColor.length||1!=this.particleColor[0].min.r||1!=this.particleColor[0].min.g||
1!=this.particleColor[0].min.b||1!=this.particleColor[0].max.r||1!=this.particleColor[0].max.g||1!=this.particleColor[0].max.b)){b.colorR=[];b.colorG=[];b.colorB=[];for(d=0;d<this.particleColor.length;d++)b.colorR.push({time:this.particleColor[d].time,value:h(this.particleColor[d].min.r,this.particleColor[d].max.r)}),b.colorG.push({time:this.particleColor[d].time,value:h(this.particleColor[d].min.g,this.particleColor[d].max.g)}),b.colorB.push({time:this.particleColor[d].time,value:h(this.particleColor[d].min.b,
this.particleColor[d].max.b)})}if(this.particleColor&&this.particleColor.length){b.colorA=[];for(d=0;d<this.particleColor.length;d++)b.colorA.push({time:this.particleColor[d].time,value:h(this.particleColor[d].min.a,this.particleColor[d].max.a)})}if(this.particleSize&&this.particleSize.length){b.sizeX=[];b.sizeY=[];for(d=0;d<this.particleSize.length;d++)b.sizeX.push({time:this.particleSize[d].time,value:h(this.particleSize[d].min.x,this.particleSize[d].max.x)}),b.sizeY.push({time:this.particleSize[d].time,
value:h(this.particleSize[d].min.y,this.particleSize[d].max.y)})}if(this.particleDrag&&this.particleDrag.length){b.drag=[];for(d=0;d<this.particleDrag.length;d++)b.drag.push({time:this.particleDrag[d].time,value:h(this.particleDrag[d].min,this.particleDrag[d].max)})}this.particleVelocity?(b.velocityX=h(this.particleVelocity.min.x,this.particleVelocity.max.x),b.velocityY=h(this.particleVelocity.min.y,this.particleVelocity.max.y)):b.velocityX=b.velocityY=0;b.angularVelocity=this.particleSpin?h(this.particleSpin.min,
this.particleSpin.max):0;this.inheritEmitterMotion&&(d=this.owner.getVelocity(),b.velocityX+=d.x,b.velocityY+=d.y,b.angularVelocity+=this.owner.getAngularVelocity());this.initialRotation&&(b.rotation=this.owner.getRotation()+h(this.initialRotation.min,this.initialRotation.max));this.area&&(b.positionX=h(this.area.minX,this.area.maxX)+g.x,b.positionY=h(this.area.minY,this.area.maxY)+g.y);this.particleLifetime&&(b.lifetime=h(this.particleLifetime.min,this.particleLifetime.max));b.layer=this.layer;b.image=
this.particleImage;b.additive=this.additive;b.forces=this.forces;b.owner=this;wade.particles.addParticle(b)}};this.onUpdate=function(){var f=h(this.emissionRate.min,this.emissionRate.max)*wade.c_timeStep+n,j=Math.floor(f);n=f-Math.floor(f);this.emit(j);this.emitterLifetime&&0>(this.emitterLifetime-=wade.c_timeStep)&&wade.removeSceneObject(this.owner)};var h=function(f,h){return Math.random()*(h-f)+f}};
