// Image effects plug-in for WADE (version 1.0) - Copyright Clockwork Chilli ltd 2012-2014 - all rights reserved. You must obtain a valid license at www.clockworkchilli.com to redistribute this file 
// Image effects plug-in for WADE (version 1.0) - Copyright Clockwork Chilli ltd 2012-2014 - all rights reserved. You must obtain a valid license at www.clockworkchilli.com to redistribute this file
Wade_ifx=function(){this.resizeFast=function(a,k,d,j){a=new Sprite(a);a.setSize(d,j);a.drawToImage(k,!0)};this.resizeNearestNeighbor=function(a,k,d,j){var e=wade.getImageData(a),a=e.width,f=e.height,e=e.data,c=document.createElement("canvas");c.width=d;c.height=j;for(var h=c.getContext("2d"),i=h.getImageData(0,0,d,j),l=i.data,n=(a-1)/(d-1),f=(f-1)/(j-1),m=0;m<d;m++)for(var p=0;p<j;p++){var q=4*(p*d+m),u=4*(Math.floor(p*f)*a+Math.floor(m*n));l[q]=e[u];l[q+1]=e[u+1];l[q+2]=e[u+2];l[q+3]=e[u+3]}h.putImageData(i,
0,0);wade.setImage(k,c)};this.resizeBilinear=function(a,k,d,j){var e=wade.getImageData(a),a=e.width,f=e.height,e=e.data,c=document.createElement("canvas");c.width=d;c.height=j;for(var h=c.getContext("2d"),i=h.getImageData(0,0,d,j),l=i.data,n=(a-1)/(d-1),m=(f-1)/(j-1),p=0;p<d;p++)for(var q=0;q<j;q++)for(var u=4*(q*d+p),t=p*n,v=q*m,x=Math.floor(t),y=Math.floor(v),z=Math.min(x+1,a-1),w=Math.min(y+1,f-1),t=x-t,v=y-v,A=4*(y*a+x),x=4*(w*a+x),y=4*(y*a+z),z=4*(w*a+z),w=0;4>w;w++)l[u+w]=(e[A+w]*(1-t)+e[y+
w]*t)*(1-v)+(e[x+w]*(1-t)+e[z+w]*t)*v;h.putImageData(i,0,0);wade.setImage(k,c)};this.blur=function(a,k,d,j,e){var f,c,h,i,l,n,m,p;this.resizeFast(a,"__imageProcessing_temp",j,e);var a=wade.getImageData("__imageProcessing_temp"),q=a.data;f=new Sprite;f.setSize(j,e);f.drawToImage(k,!0);var u=wade.getImageData(k).data,t=[1];i=[];for(f=0;f<2*d-2;f++){for(c=0;c<=f+1;c++)i[c]=(t[c-1]||0)+(t[c]||0);m=t;t=i;i=m}for(f=c=0;f<t.length;f++)c+=t[f];for(f=0;f<t.length;f++)t[f]/=c;for(f=0;f<j;f++)for(c=0;c<e;c++){for(h=
i=l=n=m=0;h<t.length;h++)p=f+h-d+1,p=Math.max(0,Math.min(p,j-1)),p+=c*j,p*=4,i+=q[p]*t[h],l+=q[p+1]*t[h],n+=q[p+2]*t[h],m+=q[p+3]*t[h];h=4*(f+c*j);u[h]=Math.floor(i);u[h+1]=Math.floor(l);u[h+2]=Math.floor(n);u[h+3]=Math.floor(m)}for(f=0;f<j;f++)for(c=0;c<e;c++){for(h=i=l=n=m=0;h<t.length;h++)p=c+h-d+1,p=Math.max(0,Math.min(p,e-1)),p*=j,p+=f,p*=4,i+=u[p]*t[h],l+=u[p+1]*t[h],n+=u[p+2]*t[h],m+=u[p+3]*t[h];h=4*(f+c*j);q[h]=Math.floor(i);q[h+1]=Math.floor(l);q[h+2]=Math.floor(n);q[h+3]=Math.floor(m)}wade.putImageData(k,
a)};this.directionalBlur=function(a,k,d,j,e,f){var c,h,i,l,n,m,p,q,d=wade.vec2.normalizeIfPossible(d);this.resizeFast(a,"__imageProcessing_temp",e,f);a=wade.getImageData("__imageProcessing_temp").data;c=new Sprite;c.setSize(e,f);c.drawToImage(k,!0);var u=wade.getImageData(k),t=u.data,v=[1];l=[];for(c=0;c<2*j-2;c++){for(h=0;h<=c+1;h++)l[h]=(v[h-1]||0)+(v[h]||0);m=v;v=l;l=m}for(c=h=0;c<j;c++)h+=v[c];for(c=0;c<j;c++)l[c]=v[j-c-1]/h;v=l;v.length=j;for(c=0;c<e;c++)for(h=0;h<f;h++){for(i=j=l=n=m=0;i<v.length;i++)p=
c-i*d.x,q=h-i*d.y,p=Math.round(Math.max(0,Math.min(p,e-1))),q=Math.round(Math.max(0,Math.min(q,f-1))),s=4*(p+q*e),j+=a[s]*v[i],l+=a[s+1]*v[i],n+=a[s+2]*v[i],m+=a[s+3]*v[i];i=4*(c+h*e);t[i]=Math.floor(j);t[i+1]=Math.floor(l);t[i+2]=Math.floor(n);t[i+3]=Math.floor(m)}wade.putImageData(k,u)};this.grayScale=function(a,k){var d=wade.getImageData(a),j=d.width,e=d.height,d=d.data,f=document.createElement("canvas");f.width=j;f.height=e;for(var c=f.getContext("2d"),h=c.getImageData(0,0,j,e),i=h.data,j=4*j*
e,e=0;e<j;e+=4)i[e]=i[e+1]=i[e+2]=Math.floor(0.2989*d[e]+0.587*d[e+1]+0.114*d[e+2]),i[e+3]=d[e+3];c.putImageData(h,0,0);wade.setImage(k,f)};this.hsl=function(a,k,d){var a=a/255,k=k/255,d=d/255,j=Math.min(a,Math.min(k,d)),e=Math.max(a,Math.max(k,d)),f=(e+j)/2,c;c=j==e?0:0.5>=f?(e-j)/(e+j):(e-j)/(2-e-j);a=60*(a>=k&&a>=d?(k-d)/(e-j):k>=a&&k>=d?2+(d-a)/(e-j):4+(a-k)/(e-j));0>a&&(a+=360);f=Math.round(1E3*f)/1E3;c=Math.round(1E3*c)/1E3;a=Math.floor(a);return{h:a,s:c,l:f}};this.rgb=function(a,k,d){if(!k)return k=
Math.floor(255*d),{r:k,g:k,b:k};k=0.5>d?d*(1+k):d+k-d*k;d=2*d-k;a/=360;a={r:a+0.333,g:a,b:a-0.333};0>a.b&&(a.b+=1);1<a.r&&(a.r-=1);for(var j=["r","g","b"],e={},f=0;f<j.length;f++){var c=j[f];e[c]=1>6*a[c]?d+6*(k-d)*a[c]:1>2*a[c]?k:2>3*a[c]?d+6*(k-d)*(0.666-a[c]):d;e[c]=Math.floor(255*e[c])}return e};this.colorize=function(a,k,d,j){var e=wade.getImageData(a),a=e.data,f=document.createElement("canvas");f.width=e.width;f.height=e.height;for(var c=f.getContext("2d"),h=c.getImageData(0,0,e.width,e.height),
i=h.data,e=4*e.width*e.height,l=0;l<e;l+=4){r=a[l]/255;g=a[l+1]/255;b=a[l+2]/255;var n=Math.min(r,Math.min(g,b)),n=(Math.max(r,Math.max(g,b))+n)/2,n=this.rgb(d,j,n);i[l]=n.r;i[l+1]=n.g;i[l+2]=n.b;i[l+3]=a[l+3]}c.putImageData(h,0,0);wade.setImage(k,f)};this.sepia=function(a,k){var d=wade.getImageData(a),j=d.data,e=document.createElement("canvas");e.width=d.width;e.height=d.height;for(var f=e.getContext("2d"),c=f.getImageData(0,0,d.width,d.height),h=c.data,d=4*d.width*d.height,i=0;i<d;i+=4){var l=j[i],
n=j[i+1],m=j[i+2];h[i]=Math.min(255,Math.round(0.393*l+0.769*n+0.189*m));h[i+1]=Math.min(255,Math.round(0.349*l+0.686*n+0.168*m));h[i+2]=Math.min(255,Math.round(0.272*l+0.534*n+0.131*m));h[i+3]=j[i+3]}f.putImageData(c,0,0);wade.setImage(k,e)};this.brightnessAndContrast=function(a,k,d,j){var e=wade.getImageData(a),a=e.data,f=document.createElement("canvas");f.width=e.width;f.height=e.height;for(var c=f.getContext("2d"),h=c.getImageData(0,0,e.width,e.height),i=h.data,e=4*e.width*e.height,l=0;l<e;l+=
4)i[l]=Math.min(255,Math.max(0,Math.round(j*a[l]+d))),i[l+1]=Math.min(255,Math.max(0,Math.round(j*a[l+1]+d))),i[l+2]=Math.min(255,Math.max(0,Math.round(j*a[l+2]+d))),i[l+3]=a[l+3];c.putImageData(h,0,0);wade.setImage(k,f)};this.duotone=function(a,k,d,j,e,f){var e=e||function(a){return a},f=f||function(a){return 1-e(a)},a=wade.getImageData(a),c=a.width,h=a.height,a=a.data,i=document.createElement("canvas");i.width=c;i.height=h;for(var l=i.getContext("2d"),n=l.getImageData(0,0,c,h),m=n.data,c=4*c*h,
h=0;h<c;h+=4){var p=(0.2989*a[h]+0.587*a[h+1]+0.114*a[h+2])/255,q=e(p),p=f(p);m[h]=Math.min(255,Math.max(0,Math.floor(d.r*q+j.r*p)));m[h+1]=Math.min(255,Math.max(0,Math.floor(d.g*q+j.g*p)));m[h+2]=Math.min(255,Math.max(0,Math.floor(d.b*q+j.b*p)));m[h+3]=a[h+3]}l.putImageData(n,0,0);wade.setImage(k,i)};this.gammaCorrect=function(a,k,d){var j=wade.getImageData(a),a=j.data,e=document.createElement("canvas");e.width=j.width;e.height=j.height;for(var f=e.getContext("2d"),c=f.getImageData(0,0,j.width,j.height),
h=c.data,j=4*j.width*j.height,i=0;i<j;i+=4)h[i]=Math.min(255,Math.max(0,Math.round(255*Math.pow(a[i]/255,d)))),h[i+1]=Math.min(255,Math.max(0,Math.round(255*Math.pow(a[i+1]/255,d)))),h[i+2]=Math.min(255,Math.max(0,Math.round(255*Math.pow(a[i+2]/255,d)))),h[i+3]=a[i+3];f.putImageData(c,0,0);wade.setImage(k,e)};this.multiply=function(a,k,d,j,e,f){"undefined"==typeof f&&(f=255);var c=wade.getImageData(a),a=c.data,h=document.createElement("canvas");h.width=c.width;h.height=c.height;for(var i=h.getContext("2d"),
l=i.getImageData(0,0,c.width,c.height),n=l.data,c=4*c.width*c.height,m=0;m<c;m+=4)n[m]=Math.min(255,Math.round(d*a[m]/255)),n[m+1]=Math.min(255,Math.round(j*a[m+1]/255)),n[m+2]=Math.min(255,Math.round(e*a[m+2]/255)),n[m+3]=Math.min(255,Math.round(f*a[m+3]/255));i.putImageData(l,0,0);wade.setImage(k,h)};this.blend=function(a,k,d,j,e){"undefined"==typeof j&&(j=0.5);a=new Sprite(a);k=new Sprite(k);k.setDrawFunction(wade.drawFunctions.alpha_(j,k.draw));a.drawToImage(d,!0);k.drawToImage(d,!1,null,null,
e)};this.split=function(a,k,d,j,e){for(var a=wade.getImageData(a),f=a.width,c=a.height,a=a.data,k=[{name:k},{name:d},{name:j},{name:e}],d=0;4>d;d++){j=document.createElement("canvas");j.width=f;j.height=c;var e=j.getContext("2d"),h=e.getImageData(0,0,f,c),i=h.data;k[d].canvas=j;k[d].context=e;k[d].imageData=h;k[d].data=i}f=4*f*c;for(d=0;d<f;d+=4){for(c=0;3>c;c++)k[c].data[d+c]=a[d+c],k[c].data[d+3]=a[d+3];k[3].data[d]=k[3].data[d+1]=k[3].data[d+2]=k[3].data[d+3]=a[d+3]}for(d=0;4>d;d++)k[d].context.putImageData(k[d].imageData,
0,0),wade.setImage(k[d].name,k[d].canvas)};this.select=function(a,k,d,j,e,f){var f=f||0,c=wade.getImageData(a),a=c.data,h=document.createElement("canvas");h.width=c.width;h.height=c.height;for(var i=h.getContext("2d"),l=i.getImageData(0,0,c.width,c.height),n=l.data,c=4*c.width*c.height,m=0;m<c;m+=4){var p=a[m]-d,q=a[m+1]-j,u=a[m+2]-e;Math.sqrt(p*p+q*q+u*u)<=f&&(n[m]=a[m],n[m+1]=a[m+1],n[m+2]=a[m+2],n[m+3]=a[m+3])}i.putImageData(l,0,0);wade.setImage(k,h)};this.exclude=function(a,k,d,j,e,f){var f=f||
0,c=wade.getImageData(a),a=c.data,h=document.createElement("canvas");h.width=c.width;h.height=c.height;for(var i=h.getContext("2d"),l=i.getImageData(0,0,c.width,c.height),n=l.data,c=4*c.width*c.height,m=0;m<c;m+=4){var p=a[m]-d,q=a[m+1]-j,u=a[m+2]-e;Math.sqrt(p*p+q*q+u*u)>f&&(n[m]=a[m],n[m+1]=a[m+1],n[m+2]=a[m+2],n[m+3]=a[m+3])}i.putImageData(l,0,0);wade.setImage(k,h)};this.glow=function(a,k,d,j,e,f,c){var h=(new Sprite(a)).getSize();this.select(a,"__imageProcessing_temp1",d,j,e,f);this.blur("__imageProcessing_temp1",
"__imageProcessing_temp2",c,h.x/4,h.y/4);this.resizeFast("__imageProcessing_temp2","__imageProcessing_temp1",h.x,h.y);this.blend(a,"__imageProcessing_temp1",k,1,"lighter");wade.unloadImage("__imageProcessing_temp1");wade.unloadImage("__imageProcessing_temp2")};this.bloom=function(a,k,d,j){this.glow(a,k,255,255,255,d,j)};this.filter=function(a,k,d,j){for(var j=j||0,e=[],f=0;f<d.length;f++)for(var c=d.length,h=c&1?-c/2+0.5+f:-c/2+(f>=c/2?f+1:f),c=0;c<d[f].length;c++){var i=d[f].length;e.push({x:i&1?
-i/2+0.5+c:-i/2+(c>=i/2?c+1:c),y:h,k:d[f][c]})}f=wade.getImageData(a);a=f.width;d=f.height;h=f.data;i=document.createElement("canvas");i.width=a;i.height=d;for(var l=i.getContext("2d"),n=l.getImageData(0,0,a,d),m=n.data,c=0;c<a;c++)for(f=0;f<d;f++){for(var p=4*(f*a+c),q=[0,0,0,0],u=0;u<e.length;u++)for(var t=Math.max(0,Math.min(a-1,c+e[u].x)),t=4*(Math.max(0,Math.min(d-1,f+e[u].y))*a+t),v=0;3>v;v++)q[v]+=e[u].k*h[t+v];for(v=0;3>v;v++)m[p+v]=Math.max(0,Math.min(255,Math.floor(q[v]+j)));m[p+3]=h[p+
3]}l.putImageData(n,0,0);wade.setImage(k,i)};this.hueAndSaturation=function(a,k,d,j){var e=wade.getImageData(a),a=e.data,f=document.createElement("canvas");f.width=e.width;f.height=e.height;for(var c=f.getContext("2d"),h=c.getImageData(0,0,e.width,e.height),i=h.data,e=4*e.width*e.height,l=0;l<e;l+=4){var n=this.hsl(a[l],a[l+1],a[l+2]);n.h+=d;n.s+=j;0>n.h?n.h+=360:360<n.h&&(n.h-=360);n.s=Math.min(1,Math.max(0,n.s));n=this.rgb(n.h,n.s,n.l);i[l]=n.r;i[l+1]=n.g;i[l+2]=n.b;i[l+3]=a[l+3]}c.putImageData(h,
0,0);wade.setImage(k,f)};this.sharpen=function(a,k){this.filter(a,k,[[-1,-1,-1],[-1,9,-1],[-1,-1,-1]])};this.edgeDetect=function(a,k){this.filter(a,k,[[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])};this.emboss=function(a,k){this.filter(a,k,[[-2,-2,0],[-2,6,0],[0,0,0]])};this.soften=function(a,k){this.filter(a,k,[[1/9,1/9,1/9],[1/9,1/9,1/9],[1/9,1/9,1/9]])}};wade.ifx=new Wade_ifx;
